image: gradle:jdk12

before_script:
  - cd ./notisblokk/
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew -Pci=gitlab build
