@startuml

title Packages - Class Diagram

folder coreModule {
  package json <<Rectangle>> {
    class NoteDeserializer
    class NoteSerializer
  }
  package core <<Rectangle>> {
    class Category
    class Note
    class Notebook
  }
}

folder fxuiModule {
  package ui <<Rectangle>> {
    class FxApp
    class FxAppController
    class NoteCell
    class NoteDataAccess
    class TabSetText
    class TabWithCategory
  }
}

folder restapiModule {
  package restapi <<Rectangle>> {
    class CustomErrorResponse
    class CustomGlobalExceptionHandler
    class NoteController
    class NoteService
    class NotesSpringBootApp
    class RestNoteNotFoundException
  }
}

coreModule -[hidden]-> fxuiModule
fxuiModule -[hidden]-> restapiModule

@enduml